using Newtonsoft.Json;

namespace SteamVRHAAgent.VR;

/// <summary>
/// Writes the SteamVR application manifest (plus a small launcher script) that lets SteamVR start the agent.
/// </summary>
public static class SteamVRManifest
{
    public const string SystemdUnit = Paths.AppId + ".service";

    public static void Write()
    {
        Directory.CreateDirectory(Paths.DataDir);
        WriteLauncher();

        var iconName = Path.GetFileName(Paths.IconFile);
        if (File.Exists(Paths.IconFile))
            File.Copy(Paths.IconFile, Path.Combine(Paths.DataDir, iconName), overwrite: true);

        var manifest = new
        {
            applications = new[]
            {
                new Dictionary<string, object>
                {
                    ["app_key"] = VRRuntime.AppKey,
                    ["launch_type"] = "binary",
                    // Relative paths are resolved against the manifest's directory.
                    ["binary_path_linux"] = Path.GetFileName(Paths.LauncherScript),
                    ["is_dashboard_overlay"] = true,
                    ["image_path"] = iconName,
                    ["strings"] = new Dictionary<string, object>
                    {
                        ["en_us"] = new
                        {
                            name = "Home Assistant Agent for SteamVR",
                            description = "Connects SteamVR to Home Assistant",
                        },
                    },
                },
            },
        };

        File.WriteAllText(Paths.ManifestFile, JsonConvert.SerializeObject(manifest, Formatting.Indented) + "\n");
    }

    private static void WriteLauncher()
    {
        var script = $"""
            #!/bin/sh
            # Generated by {Paths.AppId}; started by SteamVR through {Path.GetFileName(Paths.ManifestFile)}.
            # SteamVR's environment points at Steam runtime libraries, which the agent must not pick up.
            unset LD_LIBRARY_PATH LD_PRELOAD

            # Prefer the systemd user service when it is installed, so there is only ever one instance.
            if command -v systemctl >/dev/null 2>&1 && systemctl --user cat {SystemdUnit} >/dev/null 2>&1; then
                exec systemctl --user start {SystemdUnit}
            fi

            exec {ShellQuote(Paths.Executable)} --launched-by-steamvr
            """;
        File.WriteAllText(Paths.LauncherScript, script.ReplaceLineEndings("\n") + "\n");
        File.SetUnixFileMode(Paths.LauncherScript,
            UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute |
            UnixFileMode.GroupRead | UnixFileMode.GroupExecute | UnixFileMode.OtherRead | UnixFileMode.OtherExecute);
    }

    private static string ShellQuote(string value) => "'" + value.Replace("'", "'\\''") + "'";
}
